### ISSUE TITLE
Please update terraform script for runing four qitmeer nodes both the AWS

### ISSUE THREAD

**Issue by eric7733** [Qitmeer/qitmeer-docker-test#48]
objective:
Run four Qitmeer-DAG nodes,
How to quickly run the Qitmeer-DAG Network, see [here.](https://github.com/HalalChain/qitmeer-docker-test/blob/master/README.md).

**Comment by snowsky** [comment]
Just found a way to list all the IP addresses of the spot instances for testing. Will put up the codes later.
